<a href="https://colab.research.google.com/github/143biswajit/Extra-assignment/blob/main/NumPY_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

BASICS OF NUMPY

In [2]:
# load the numpy
import numpy as np

Array manipulation
    TRANSPOSE ARRAY

In [3]:

#creat 2 d array
bro=np.array(np.random.randint(15,60,(5,3)))
print(f"the defind array is \n{bro}")
print(f"\n the shape of the array is {bro.shape}")


the defind array is 
[[59 51 58]
 [45 37 37]
 [32 55 49]
 [56 36 17]
 [17 30 55]]

 the shape of the array is (5, 3)


In [4]:
# transpose array in another martrix
ajit_bro=np.transpose(bro)
print(f" the transpose of the array is \n{ajit_bro}")
print(" \n the shape of the array is {ajit_bro}")


 the transpose of the array is 
[[59 45 32 56 17]
 [51 37 55 36 30]
 [58 37 49 17 55]]
 
 the shape of the array is {ajit_bro}


np.reshape(shape)

In [5]:
# creat a two dimentional array
boss_=np.array(np.random.randint(10,45,(3,8)))
print(f"the defined array is \n{boss_}")
print(f"\n the shape of the array is {boss_.shape}")

the defined array is 
[[15 31 19 39 43 23 23 35]
 [32 23 12 18 37 42 27 37]
 [42 37 37 37 16 41 23 13]]

 the shape of the array is (3, 8)


In [6]:
# now we can reshape  this to 1d ,2d,3d array
new_shape= (2,6,2)
reshaped_boss_=np.reshape(boss_,new_shape)
print(f"the reshaped array is \n{reshaped_boss_}")
print(f"\n the shape of the array is {reshaped_boss_.shape}")

the reshaped array is 
[[[15 31]
  [19 39]
  [43 23]
  [23 35]
  [32 23]
  [12 18]]

 [[37 42]
  [27 37]
  [42 37]
  [37 37]
  [16 41]
  [23 13]]]

 the shape of the array is (2, 6, 2)


In [9]:
# numpay reshape
# initialise a 3 d array
new_array=np.array(np.random.randint(10,45,(2,4,6)))
print(f"the defined array is \n{new_array}")
print(f"\n the shape of the array is {new_array.shape}")

the defined array is 
[[[11 43 27 15 32 39]
  [18 40 14 37 23 39]
  [23 16 21 18 22 15]
  [22 12 43 23 13 39]]

 [[18 19 27 12 34 36]
  [28 15 33 31 33 36]
  [37 15 23 24 19 13]
  [42 41 16 32 32 12]]]

 the shape of the array is (2, 4, 6)


In [10]:
#np flatten
#initialise a 3d array
new_array=np.array(np.random.randint(10,45,(2,4,6)))
print(f"the  defined array is \n{new_array}")
print(f"\n the shape of the array is {new_array.shape}")


the  defined array is 
[[[36 44 36 37 30 44]
  [40 34 31 38 42 14]
  [17 38 16 22 37 31]
  [44 21 37 30 32 20]]

 [[34 33 42 29 36 14]
  [31 22 33 16 40 19]
  [41 38 29 31 21 17]
  [29 23 25 11 13 19]]]

 the shape of the array is (2, 4, 6)
