<a href="https://colab.research.google.com/github/143biswajit/Extra-assignment/blob/main/NumPY_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

BASICS OF NUMPY

In [2]:
# load the numpy
import numpy as np

Array manipulation
    TRANSPOSE ARRAY

In [3]:

#creat 2 d array
bro=np.array(np.random.randint(15,60,(5,3)))
print(f"the defind array is \n{bro}")
print(f"\n the shape of the array is {bro.shape}")


the defind array is 
[[37 27 16]
 [39 57 52]
 [31 58 47]
 [57 47 26]
 [40 50 27]]

 the shape of the array is (5, 3)


In [4]:
# transpose array in another martrix
ajit_bro=np.transpose(bro)
print(f" the transpose of the array is \n{ajit_bro}")
print(" \n the shape of the array is {ajit_bro}")


 the transpose of the array is 
[[37 39 31 57 40]
 [27 57 58 47 50]
 [16 52 47 26 27]]
 
 the shape of the array is {ajit_bro}


np.reshape(shape)

In [24]:
# creat a two dimentional array
boss_=np.array(np.random.randint(10,45,(3,8)))
print(f"the defined array is \n{boss_}")
print(f"\n the shape of the array is {boss_.shape}")

the defined array is 
[[23 14 36 34 17 38 18 11]
 [20 18 40 12 31 35 34 28]
 [32 21 17 36 18 17 38 38]]

 the shape of the array is (3, 8)


In [25]:
# now we can reshape  this to 1d ,2d,3d array
new_shape= (2,6,2)
reshaped_boss_=np.reshape(boss_,new_shape)
print(f"the reshaped array is \n{reshaped_boss_}")
print(f"\n the shape of the array is {reshaped_boss_.shape}")

the reshaped array is 
[[[23 14]
  [36 34]
  [17 38]
  [18 11]
  [20 18]
  [40 12]]

 [[31 35]
  [34 28]
  [32 21]
  [17 36]
  [18 17]
  [38 38]]]

 the shape of the array is (2, 6, 2)
