<a href="https://colab.research.google.com/github/143biswajit/Extra-assignment/blob/main/NumPY_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

BASICS OF NUMPY

In [1]:
# load the numpy
import numpy as np

Array manipulation
    TRANSPOSE ARRAY

In [3]:

#creat 2 d array
bro=np.array(np.random.randint(15,60,(5,3)))
print(f"the defind array is \n{bro}")
print(f"\n the shape of the array is {bro.shape}")


the defind array is 
[[42 44 57]
 [40 31 49]
 [56 49 42]
 [42 31 52]
 [43 53 30]]

 the shape of the array is (5, 3)


In [4]:
# transpose array in another martrix
ajit_bro=np.transpose(bro)
print(f" the transpose of the array is \n{ajit_bro}")
print(" \n the shape of the array is {ajit_bro}")


 the transpose of the array is 
[[42 40 56 42 43]
 [44 31 49 31 53]
 [57 49 42 52 30]]
 
 the shape of the array is {ajit_bro}
